mongodb:
  uri-mode: false
  normal:
    host: 127.0.0.1
    port: '27017'
    database: Eggwars
    authentication:
      enabled: false
      username: ''
      password: ''
  uri:
    database: Eggwars
    connection_string: mongodb://127.0.0.1:27017/Eggwars

sign-lines:
  - "%name% &8(%level%)"
  - "&0[&l%progress%&r&0]"
  - "&8Click derecho"
  - "%speed% -> %speed_next%"

spawn:
  world: "spawn"
  cords: "10,74,1"
  border: 126

shopkeepers:
  rows: 5
  title: "Seleciona la skin de tu tienda"
  preview-seconds-duration: 5 
  name: "&e&lTienda"

win-celebration-duration-in-seconds: 10