mongodb:
  database: Eggwars
  connection-string: mongodb://127.0.0.1:27017/Eggwars

sign-lines:
  - "%name% &8(%level%)"
  - "&0[&l%progress%&r&0]"
  - "&8Click derecho"
  - "%speed% -> %speed_next%"

disable-default-world: "world"

join: " &a se ha unido"

tab:
  header:
    - ""
    - "&b&lMine&6&lLC"
    - ""
  footer:
    - ""
    - "&fGracias por elegirnos &c❤"
    - "&7Para ayuda: /help"

spawn:
  world: "spawn"
  cords: "10,74,1,23,23"
  border: 126

pregame:
  world: "pregame"
  cords: "0,65,0,19,1.7"
  border: 200

shopkeepers:
  rows: 5
  title: "Seleciona la skin de tu tienda"
  preview-seconds-duration: 5 
  name: "&e&lTienda"

generators:
  pickup-distance-blocks: 2
  view-distance-blocks: 5

win-celebration-duration-in-seconds: 10