sign-lines:
  - ""
  - "%name% &8(%level%)"
  - "&8%amount% &0/ &8%speed%s"
  - ""

spawn-world: "spawnegg"
spawn: "-1,65,8"
spawn-border: 60

respawn:
  seconds: 3
  title: "&e&c&lRespawn in %seconds% &e"
  subtitle: "&7Remember learn pvp"